"""First-run discovery and configuration helpers for PaperRoach."""
from __future__ import annotations

import json
import os
import sys
import tempfile
import tomllib
from pathlib import Path

from kb.config import ConfigError


def obsidian_config_paths(
    *,
    platform: str | None = None,
    environ: dict[str, str] | None = None,
    home: Path | None = None,
) -> list[Path]:
    """Return best-effort locations of Obsidian's desktop config file."""
    platform = platform or sys.platform
    environ = os.environ if environ is None else environ
    home = Path.home() if home is None else Path(home)

    if platform == "win32":
        base = Path(environ.get("APPDATA") or home / "AppData" / "Roaming")
        return [base / "obsidian" / "obsidian.json"]
    if platform == "darwin":
        return [
            home
            / "Library"
            / "Application Support"
            / "obsidian"
            / "obsidian.json"
        ]

    base = Path(environ.get("XDG_CONFIG_HOME") or home / ".config")
    return [
        base / "obsidian" / "obsidian.json",
        home
        / ".var"
        / "app"
        / "md.obsidian.Obsidian"
        / "config"
        / "obsidian"
        / "obsidian.json",
        home
        / "snap"
        / "obsidian"
        / "current"
        / ".config"
        / "obsidian"
        / "obsidian.json",
    ]


def _path_identity(path: Path) -> str:
    try:
        resolved = path.resolve()
    except OSError:
        resolved = path.absolute()
    return os.path.normcase(str(resolved))


def _valid_obsidian_vault(path: Path) -> bool:
    return path.is_dir() and (path / ".obsidian").is_dir()


def validate_obsidian_vault(value: str | Path) -> Path:
    """Validate an existing Obsidian vault without creating typo paths."""
    vault = Path(value).expanduser()
    if not vault.exists():
        raise ConfigError(f"Obsidian vault does not exist: {vault}")
    if not vault.is_dir():
        raise ConfigError(f"Obsidian vault is not a directory: {vault}")
    if not (vault / ".obsidian").is_dir():
        raise ConfigError(
            f"Not an Obsidian vault (missing .obsidian directory): {vault}"
        )
    return vault.resolve()


def discover_obsidian_vaults(
    *,
    cwd: Path | None = None,
    environ: dict[str, str] | None = None,
    config_paths: list[Path] | None = None,
) -> list[Path]:
    """Discover existing Obsidian vaults without guessing or creating them."""
    environ = os.environ if environ is None else environ
    cwd = Path.cwd() if cwd is None else Path(cwd)
    found: list[Path] = []
    seen: set[str] = set()

    def add(candidate: str | Path | None) -> None:
        if not candidate:
            return
        if not isinstance(candidate, (str, os.PathLike)):
            return
        try:
            path = Path(candidate).expanduser()
        except (OSError, TypeError, ValueError):
            return
        if not _valid_obsidian_vault(path):
            return
        identity = _path_identity(path)
        if identity not in seen:
            seen.add(identity)
            found.append(path.resolve())

    add(environ.get("KB_VAULT"))

    try:
        current = cwd.resolve()
    except OSError:
        current = cwd.absolute()
    for parent in (current, *current.parents):
        if _valid_obsidian_vault(parent):
            add(parent)
            break

    paths = config_paths if config_paths is not None else obsidian_config_paths(
        environ=environ
    )
    entries: list[dict] = []
    for config_path in paths:
        try:
            payload = json.loads(Path(config_path).read_text(encoding="utf-8"))
        except (OSError, UnicodeError, json.JSONDecodeError):
            continue
        vaults = payload.get("vaults", {})
        if isinstance(vaults, dict):
            entries.extend(item for item in vaults.values() if isinstance(item, dict))

    def recency(entry: dict) -> tuple[int, int]:
        timestamp = entry.get("ts")
        if not isinstance(timestamp, (int, float)):
            timestamp = 0
        return (0 if entry.get("open") else 1, -int(timestamp))

    for entry in sorted(entries, key=recency):
        add(entry.get("path"))
    return found


def minimal_config(vault: Path) -> str:
    """Render the small config a new user needs; defaults cover the rest."""
    portable = str(vault).replace("\\", "/")
    encoded = json.dumps(portable, ensure_ascii=False)
    return (
        "# Generated by paperroach setup.\n"
        "# See kb/templates/kb.example.toml for every optional setting.\n"
        f"vault_path = {encoded}\n"
    )


def _configured_vault(config_path: Path) -> Path | None:
    try:
        with config_path.open("rb") as handle:
            value = tomllib.load(handle).get("vault_path")
    except (OSError, tomllib.TOMLDecodeError):
        return None
    return Path(value).expanduser() if value else None


def write_user_config(
    vault: Path,
    config_path: Path,
    *,
    force: bool = False,
) -> bool:
    """Atomically write a minimal user config.

    Returns True when a file was written and False for an idempotent rerun
    against a config that already selects the same vault.
    """
    config_path = Path(config_path).expanduser()
    if config_path.exists() and not force:
        existing = _configured_vault(config_path)
        if existing is not None and _path_identity(existing) == _path_identity(vault):
            return False
        raise ConfigError(
            f"Config already exists and selects another or invalid vault: {config_path}. "
            "Review it, then rerun with --force to replace it."
        )

    config_path.parent.mkdir(parents=True, exist_ok=True)
    temporary: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            newline="\n",
            dir=config_path.parent,
            prefix=f".{config_path.name}.",
            suffix=".tmp",
            delete=False,
        ) as handle:
            temporary = Path(handle.name)
            handle.write(minimal_config(vault))
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, config_path)
    finally:
        if temporary is not None and temporary.exists():
            temporary.unlink()
    return True
